-- Migration: Create product_snapshot table for historical price tracking
-- This table stores historical price snapshots for products

-- Create product_snapshot table
CREATE TABLE IF NOT EXISTS "public"."product_snapshot" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "asin" text not null,
  "final_price" double precision not null
);

-- Create primary key
CREATE UNIQUE INDEX product_snapshot_pkey ON public.product_snapshot USING btree (id);
ALTER TABLE "public"."product_snapshot" ADD CONSTRAINT "product_snapshot_pkey" PRIMARY KEY USING INDEX "product_snapshot_pkey";

-- Add foreign key constraint to products table
ALTER TABLE "public"."product_snapshot" 
  ADD CONSTRAINT "product_snapshot_asin_fkey" 
  FOREIGN KEY (asin) 
  REFERENCES products(asin) 
  ON UPDATE CASCADE 
  ON DELETE CASCADE;

-- Enable Row Level Security
ALTER TABLE "public"."product_snapshot" ENABLE ROW LEVEL SECURITY;

-- RLS Policies for product_snapshot table
-- Anyone authenticated can view product snapshots
CREATE POLICY "Authenticated users can view product snapshots"
  ON product_snapshot FOR SELECT
  USING (auth.role() = 'authenticated' OR auth.role() = 'anon');

-- Service role can insert/update product snapshots (for edge functions)
CREATE POLICY "Service role can manage product snapshots"
  ON product_snapshot FOR ALL
  USING (auth.jwt()->>'role' = 'service_role');

-- Create index on asin for faster lookups
CREATE INDEX IF NOT EXISTS idx_product_snapshot_asin ON product_snapshot(asin);

-- Create index on created_at for time-based queries
CREATE INDEX IF NOT EXISTS idx_product_snapshot_created_at ON product_snapshot(created_at DESC);

-- Grant permissions
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE 
  ON TABLE "public"."product_snapshot" 
  TO "anon", "authenticated", "service_role";

-- Comment explaining the schema
COMMENT ON TABLE product_snapshot IS 'Stores historical price snapshots for products to track price changes over time';

